/* watchDocs — mock telemetry for registered GitHub services.
   Plain global script (not Babel). Exposes window.WD_DATA. */
(function () {
  "use strict";

  // ---- helpers to generate plausible series -------------------------------
  function series(n, base, jitter, trend) {
    const out = [];
    let v = base;
    for (let i = 0; i < n; i++) {
      v += (Math.random() - 0.5) * jitter + (trend || 0);
      out.push(Math.max(0, +v.toFixed(2)));
    }
    return out;
  }
  function spike(n, base, jitter, at, mag) {
    const out = series(n, base, jitter);
    for (let i = at; i < Math.min(n, at + 6); i++) out[i] += mag * (1 - (i - at) / 6);
    return out.map((x) => +Math.max(0, x).toFixed(2));
  }

  const now = Date.now();
  const min = 60 * 1000;

  // ---- services -----------------------------------------------------------
  const services = [
    {
      id: "media-cdn",
      name: "media-cdn",
      title: "Media CDN",
      repo: "watchdocs/media-cdn",
      lang: "Go",
      langColor: "#00ADD8",
      env: "production",
      region: "ap-northeast-2",
      status: "critical",
      health: 41,
      uptime: 99.21,
      uptime30: 99.71,
      version: "v2.14.0",
      versionState: "rolling-back",
      lastDeploy: now - 14 * min,
      reqPerMin: 18420,
      apiCalls24h: 24800000,
      errorRate: 4.8,
      latencyP95: 812,
      activeUsers: 9120,
      cpu: 91,
      mem: 86,
      disk: 73,
      net: 64,
      openIssues: 7,
      newFeedback: 12,
      cpuSeries: spike(48, 60, 8, 30, 35),
      reqSeries: spike(48, 16000, 1800, 30, 6000),
      errSeries: spike(48, 0.8, 0.4, 30, 6),
      latSeries: spike(48, 300, 60, 30, 600),
    },
    {
      id: "chat-realtime",
      name: "chat-realtime",
      title: "Realtime Chat",
      repo: "watchdocs/chat-realtime",
      lang: "TypeScript",
      langColor: "#3178C6",
      env: "production",
      region: "ap-northeast-2",
      status: "warning",
      health: 72,
      uptime: 99.86,
      uptime30: 99.93,
      version: "v4.2.1",
      versionState: "deployed",
      lastDeploy: now - 3 * 60 * min,
      reqPerMin: 9240,
      apiCalls24h: 12100000,
      errorRate: 1.3,
      latencyP95: 268,
      activeUsers: 21400,
      cpu: 68,
      mem: 74,
      disk: 41,
      net: 52,
      openIssues: 4,
      newFeedback: 6,
      cpuSeries: series(48, 60, 10, 0.3),
      reqSeries: series(48, 9000, 900),
      errSeries: series(48, 1.1, 0.5),
      latSeries: series(48, 240, 40, 1),
    },
    {
      id: "payments-api",
      name: "payments-api",
      title: "Payments API",
      repo: "watchdocs/payments-api",
      lang: "Rust",
      langColor: "#DEA584",
      env: "production",
      region: "ap-northeast-2",
      status: "healthy",
      health: 98,
      uptime: 99.99,
      uptime30: 99.98,
      version: "v1.9.4",
      versionState: "deployed",
      lastDeploy: now - 26 * 60 * min,
      reqPerMin: 4120,
      apiCalls24h: 5900000,
      errorRate: 0.04,
      latencyP95: 88,
      activeUsers: 3400,
      cpu: 34,
      mem: 47,
      disk: 38,
      net: 22,
      openIssues: 1,
      newFeedback: 0,
      cpuSeries: series(48, 32, 6),
      reqSeries: series(48, 4000, 400),
      errSeries: series(48, 0.05, 0.04),
      latSeries: series(48, 84, 12),
    },
    {
      id: "auth-service",
      name: "auth-service",
      title: "Auth Service",
      repo: "watchdocs/auth-service",
      lang: "Go",
      langColor: "#00ADD8",
      env: "production",
      region: "ap-northeast-2",
      status: "healthy",
      health: 96,
      uptime: 99.97,
      uptime30: 99.96,
      version: "v3.0.2",
      versionState: "deployed",
      lastDeploy: now - 8 * 60 * min,
      reqPerMin: 6700,
      apiCalls24h: 8800000,
      errorRate: 0.12,
      latencyP95: 102,
      activeUsers: 18200,
      cpu: 44,
      mem: 52,
      disk: 35,
      net: 31,
      openIssues: 2,
      newFeedback: 1,
      cpuSeries: series(48, 42, 7),
      reqSeries: series(48, 6500, 600),
      errSeries: series(48, 0.12, 0.06),
      latSeries: series(48, 98, 14),
    },
    {
      id: "search-index",
      name: "search-index",
      title: "Search Index",
      repo: "watchdocs/search-index",
      lang: "Java",
      langColor: "#B07219",
      env: "production",
      region: "ap-northeast-2",
      status: "warning",
      health: 69,
      uptime: 99.74,
      uptime30: 99.81,
      version: "v0.18.0",
      versionState: "deployed",
      lastDeploy: now - 5 * 60 * min,
      reqPerMin: 3100,
      apiCalls24h: 4200000,
      errorRate: 0.9,
      latencyP95: 430,
      activeUsers: 7600,
      cpu: 77,
      mem: 81,
      disk: 88,
      net: 28,
      openIssues: 5,
      newFeedback: 3,
      cpuSeries: series(48, 70, 9, 0.2),
      reqSeries: series(48, 3000, 350),
      errSeries: series(48, 0.8, 0.3),
      latSeries: series(48, 410, 60),
    },
    {
      id: "analytics-pipeline",
      name: "analytics-pipeline",
      title: "Analytics Pipeline",
      repo: "watchdocs/analytics-pipeline",
      lang: "Python",
      langColor: "#3572A5",
      env: "production",
      region: "ap-northeast-2",
      status: "healthy",
      health: 91,
      uptime: 99.95,
      uptime30: 99.9,
      version: "v2.7.1",
      versionState: "deployed",
      lastDeploy: now - 40 * 60 * min,
      reqPerMin: 1450,
      apiCalls24h: 2100000,
      errorRate: 0.21,
      latencyP95: 640,
      activeUsers: 210,
      cpu: 58,
      mem: 63,
      disk: 52,
      net: 19,
      openIssues: 3,
      newFeedback: 2,
      cpuSeries: series(48, 55, 8),
      reqSeries: series(48, 1400, 200),
      errSeries: series(48, 0.2, 0.1),
      latSeries: series(48, 620, 80),
    },
    {
      id: "notification-worker",
      name: "notification-worker",
      title: "Notification Worker",
      repo: "watchdocs/notification-worker",
      lang: "TypeScript",
      langColor: "#3178C6",
      env: "production",
      region: "ap-northeast-2",
      status: "degraded",
      health: 63,
      uptime: 99.62,
      uptime30: 99.78,
      version: "v1.4.0",
      versionState: "deploying",
      lastDeploy: now - 2 * min,
      reqPerMin: 2280,
      apiCalls24h: 3300000,
      errorRate: 1.9,
      latencyP95: 355,
      activeUsers: 0,
      cpu: 61,
      mem: 70,
      disk: 44,
      net: 24,
      openIssues: 6,
      newFeedback: 4,
      cpuSeries: series(48, 58, 10),
      reqSeries: series(48, 2200, 300),
      errSeries: series(48, 1.7, 0.6),
      latSeries: series(48, 340, 50),
    },
    {
      id: "web-frontend",
      name: "web-frontend",
      title: "Web Frontend",
      repo: "watchdocs/web-frontend",
      lang: "TypeScript",
      langColor: "#3178C6",
      env: "production",
      region: "global / edge",
      status: "healthy",
      health: 99,
      uptime: 99.99,
      uptime30: 99.99,
      version: "v8.31.2",
      versionState: "deployed",
      lastDeploy: now - 55 * min,
      reqPerMin: 12600,
      apiCalls24h: 16400000,
      errorRate: 0.03,
      latencyP95: 64,
      activeUsers: 42800,
      cpu: 22,
      mem: 31,
      disk: 18,
      net: 47,
      openIssues: 2,
      newFeedback: 5,
      cpuSeries: series(48, 20, 5),
      reqSeries: series(48, 12000, 1200),
      errSeries: series(48, 0.03, 0.02),
      latSeries: series(48, 62, 9),
    },
  ];

  // ---- per-service incident / error breakdown ----------------------------
  const errors = {
    "media-cdn": [
      { sev: "critical", code: "ECONNRESET", title: "Upstream origin connection reset", count: 1284, delta: "+1180", lastSeen: now - 40 * 1000, endpoint: "GET /assets/:id", trace: "net/http: TLS handshake timeout\n  at originPool.dial (origin/pool.go:212)\n  at proxy.forward (proxy/forward.go:88)\n  at handler.serve (server.go:341)" },
      { sev: "critical", code: "503", title: "Service unavailable — origin pool exhausted", count: 642, delta: "+610", lastSeen: now - 70 * 1000, endpoint: "GET /stream/:key", trace: "origin pool exhausted (max=64, in-use=64)\n  at originPool.acquire (origin/pool.go:140)\n  at proxy.forward (proxy/forward.go:71)" },
      { sev: "warning", code: "499", title: "Client closed request before response", count: 388, delta: "+120", lastSeen: now - 30 * 1000, endpoint: "GET /assets/:id", trace: "context canceled\n  at handler.serve (server.go:355)" },
      { sev: "warning", code: "ETIMEDOUT", title: "Cache write timed out", count: 211, delta: "+88", lastSeen: now - 2 * min, endpoint: "internal/cache", trace: "redis: write timeout after 200ms\n  at cache.set (cache/redis.go:64)" },
      { sev: "info", code: "404", title: "Asset not found", count: 95, delta: "-12", lastSeen: now - 90 * 1000, endpoint: "GET /assets/:id", trace: "object not found in bucket\n  at storage.get (storage/s3.go:130)" },
    ],
    "chat-realtime": [
      { sev: "warning", code: "WS_1011", title: "WebSocket closed — internal error", count: 142, delta: "+44", lastSeen: now - 2 * min, endpoint: "WS /socket", trace: "unexpected EOF on frame read\n  at ws.readFrame (ws/conn.ts:88)" },
      { sev: "warning", code: "429", title: "Rate limit exceeded on message send", count: 96, delta: "+10", lastSeen: now - 4 * min, endpoint: "POST /messages", trace: "rate limiter tripped (60/min)\n  at limiter.check (rate.ts:33)" },
      { sev: "info", code: "400", title: "Malformed payload", count: 51, delta: "-3", lastSeen: now - 6 * min, endpoint: "POST /messages", trace: "invalid JSON at position 14\n  at parseBody (body.ts:22)" },
    ],
    "search-index": [
      { sev: "warning", code: "DISK_PRESSURE", title: "Index node low on disk (88%)", count: 1, delta: "new", lastSeen: now - 3 * min, endpoint: "node-3", trace: "watermark exceeded: flood-stage 85%\n  at IndexService.write (IndexService.java:410)" },
      { sev: "warning", code: "504", title: "Query gateway timeout", count: 73, delta: "+22", lastSeen: now - 5 * min, endpoint: "POST /search", trace: "query exceeded 1500ms budget\n  at QueryExecutor.run (QueryExecutor.java:128)" },
    ],
    "notification-worker": [
      { sev: "critical", code: "QUEUE_STALL", title: "Job queue not draining", count: 1, delta: "new", lastSeen: now - 90 * 1000, endpoint: "worker/main", trace: "0 jobs processed in last 120s (backlog=8420)\n  at Worker.loop (worker.ts:64)" },
      { sev: "warning", code: "SMTP_421", title: "Mail provider throttling", count: 204, delta: "+150", lastSeen: now - 1 * min, endpoint: "send/email", trace: "421 4.7.0 too many connections\n  at smtp.send (smtp.ts:88)" },
    ],
    "payments-api": [
      { sev: "info", code: "402", title: "Card declined (issuer)", count: 38, delta: "+2", lastSeen: now - 7 * min, endpoint: "POST /charge", trace: "issuer declined: insufficient_funds\n  at gateway.charge (gateway.rs:201)" },
    ],
    "auth-service": [
      { sev: "warning", code: "401", title: "Token signature mismatch", count: 64, delta: "+9", lastSeen: now - 3 * min, endpoint: "POST /verify", trace: "jwt: signature invalid\n  at verify (token.go:77)" },
    ],
    "analytics-pipeline": [
      { sev: "warning", code: "LAG", title: "Consumer lag above threshold", count: 1, delta: "new", lastSeen: now - 8 * min, endpoint: "kafka/events", trace: "consumer lag 42k > 30k\n  at Consumer.poll (consumer.py:91)" },
    ],
    "web-frontend": [
      { sev: "info", code: "CSP", title: "Content-Security-Policy report", count: 22, delta: "+4", lastSeen: now - 12 * min, endpoint: "report-uri", trace: "blocked inline script\n  at csp.report (edge.ts:40)" },
    ],
  };

  // ---- user feedback / GitHub issues -------------------------------------
  const feedback = {
    "media-cdn": [
      { type: "issue", sev: "high", title: "이미지가 간헐적으로 깨져서 로드돼요", author: "minseo_k", channel: "GitHub #482", up: 34, time: now - 8 * min, tag: "bug" },
      { type: "feedback", sev: "high", title: "동영상 재생이 자꾸 멈춥니다 (모바일)", author: "app-store", channel: "App Store · ★2", up: 21, time: now - 22 * min, tag: "performance" },
      { type: "issue", sev: "med", title: "썸네일 로딩이 느려요", author: "devops_jay", channel: "GitHub #479", up: 12, time: now - 51 * min, tag: "performance" },
      { type: "feedback", sev: "med", title: "프로필 사진 업로드 후 안 보임", author: "support", channel: "Intercom", up: 8, time: now - 70 * min, tag: "bug" },
      { type: "feedback", sev: "low", title: "갤러리 화질 옵션이 있으면 좋겠어요", author: "user_9931", channel: "In-app", up: 5, time: now - 2 * 60 * min, tag: "request" },
    ],
    "chat-realtime": [
      { type: "feedback", sev: "high", title: "메시지가 가끔 두 번 전송돼요", author: "haeun.p", channel: "Intercom", up: 28, time: now - 14 * min, tag: "bug" },
      { type: "issue", sev: "med", title: "오래된 대화 스크롤 시 끊김", author: "frontend_lee", channel: "GitHub #211", up: 9, time: now - 44 * min, tag: "performance" },
      { type: "feedback", sev: "low", title: "다크모드에서 안 읽은 표시가 잘 안 보임", author: "user_3320", channel: "In-app", up: 4, time: now - 3 * 60 * min, tag: "ui" },
    ],
    "payments-api": [
      { type: "feedback", sev: "low", title: "영수증 이메일이 늦게 와요", author: "user_771", channel: "Email", up: 3, time: now - 5 * 60 * min, tag: "request" },
    ],
    "auth-service": [
      { type: "issue", sev: "med", title: "소셜 로그인 후 가끔 로그아웃됨", author: "qa_team", channel: "GitHub #88", up: 11, time: now - 33 * min, tag: "bug" },
    ],
    "search-index": [
      { type: "feedback", sev: "high", title: "검색 결과가 누락되는 경우가 있어요", author: "pm_sora", channel: "Slack #voc", up: 19, time: now - 18 * min, tag: "bug" },
      { type: "issue", sev: "med", title: "한글 자모 분리 검색이 안 됨", author: "search_team", channel: "GitHub #57", up: 14, time: now - 90 * min, tag: "feature" },
    ],
    "analytics-pipeline": [
      { type: "issue", sev: "low", title: "대시보드 지표가 1시간 지연돼요", author: "data_min", channel: "GitHub #140", up: 6, time: now - 2 * 60 * min, tag: "bug" },
    ],
    "notification-worker": [
      { type: "feedback", sev: "high", title: "푸시 알림이 안 와요", author: "user_5521", channel: "App Store · ★1", up: 41, time: now - 6 * min, tag: "bug" },
      { type: "feedback", sev: "med", title: "이메일 알림이 중복으로 옵니다", author: "support", channel: "Intercom", up: 13, time: now - 48 * min, tag: "bug" },
    ],
    "web-frontend": [
      { type: "feedback", sev: "low", title: "설정 페이지 레이아웃이 깨져 보여요 (Safari)", author: "user_1180", channel: "In-app", up: 7, time: now - 80 * min, tag: "ui" },
      { type: "issue", sev: "low", title: "키보드 탐색 접근성 개선 요청", author: "a11y_kim", channel: "GitHub #903", up: 9, time: now - 3 * 60 * min, tag: "a11y" },
    ],
  };

  // ---- recent commits / deploy timeline ----------------------------------
  const deploys = {
    "media-cdn": [
      { kind: "rollback", sha: "a91f3c2", msg: "Rollback to v2.13.4 — origin pool regression", author: "oncall", time: now - 9 * min, state: "in-progress" },
      { kind: "deploy", sha: "7e2d11b", msg: "feat: switch origin pool to adaptive sizing", author: "minseo_k", time: now - 14 * min, state: "failed" },
      { kind: "commit", sha: "3c8a740", msg: "perf: reuse TLS sessions across origins", author: "minseo_k", time: now - 26 * min, state: "ok" },
      { kind: "commit", sha: "b1029ee", msg: "chore: bump go to 1.22", author: "devops_jay", time: now - 2 * 60 * min, state: "ok" },
    ],
    "chat-realtime": [
      { kind: "deploy", sha: "44ab9c0", msg: "fix: dedupe outgoing frames on reconnect", author: "haeun.p", time: now - 3 * 60 * min, state: "ok" },
      { kind: "commit", sha: "9920f1a", msg: "test: add reconnect storm coverage", author: "frontend_lee", time: now - 4 * 60 * min, state: "ok" },
    ],
    "notification-worker": [
      { kind: "deploy", sha: "ff3e881", msg: "fix: drain queue on SIGTERM", author: "oncall", time: now - 2 * min, state: "in-progress" },
      { kind: "commit", sha: "5d77a22", msg: "feat: exponential backoff for SMTP 421", author: "backend_oh", time: now - 30 * min, state: "ok" },
    ],
    "search-index": [
      { kind: "deploy", sha: "1aa0c93", msg: "feat: add node-4 to hot tier", author: "search_team", time: now - 5 * 60 * min, state: "ok" },
    ],
    "payments-api": [
      { kind: "deploy", sha: "c0ffee1", msg: "feat: idempotency keys on /charge", author: "pay_team", time: now - 26 * 60 * min, state: "ok" },
    ],
    "auth-service": [
      { kind: "deploy", sha: "0a1b2c3", msg: "fix: rotate signing keys", author: "sec_team", time: now - 8 * 60 * min, state: "ok" },
    ],
    "analytics-pipeline": [
      { kind: "deploy", sha: "deadbe7", msg: "perf: batch kafka commits", author: "data_min", time: now - 40 * 60 * min, state: "ok" },
    ],
    "web-frontend": [
      { kind: "deploy", sha: "fab1e50", msg: "feat: new settings layout", author: "frontend_lee", time: now - 55 * min, state: "ok" },
    ],
  };

  window.WD_DATA = { services, errors, feedback, deploys, generatedAt: now };
})();
